#!/bin/bash
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/css/f144792aa47970cec15d.css.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/css/696af6c4108c71524e4a.css.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/pages/wallet-005cfbcf5da697a31b40.js
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/main-a7240a4f85af525f5d54.js.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/webpack-3b54c13c8297fb4ce214.js.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/8a9c8dce.3263c53d15dcd5ee637c.js.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/ec23b2e1.49d2f306df97423803b8.js.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/35270ec8.2ea33f5a44b63a3301ba.js.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/b5a2aaf6.6e26d758856746b80c63.js.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/0614091c.67393a4e4c31868ac78d.js.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/pages/_app-ef2b81eb205e6567b6c9.js.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/c78d26b1.155c70378c398f6c8fcc.js.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/e971612a.ab3567407757e97c4c30.js.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/49790189.f12217e8016cfa9b9535.js.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/framework.e2b14b3899758d0ebc4c.js.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/commons.6004802f0720f4f30c26.js.map
 wget --no-check-certificate --mirror --xattr --convert-links --adjust-extension --page-requisites --no-parent https://opensea.io/_next/static/chunks/89.5dabcd60698a74e8de7f.js
